export const todayForeCast = [
  {
    id: 1,
    time: '01:00 PM',
    icon: require('../assets/cloudy.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 2,
    time: '02:00 PM',
    icon: require('../assets/rain.png'),
    weather: 'Mostly Sunny',
    temp: '22°C',
  },
  {
    id: 3,
    time: '03:00 PM',
    icon: require('../assets/sun.png'),
    weather: 'Partly Cloudy',
    temp: '22°C',
  },
  {
    id: 4,
    time: '04:00 PM',
    icon: require('../assets/rising-sun.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 5,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 6,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 7,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 8,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 9,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 10,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 11,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 12,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 13,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 14,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
  {
    id: 15,
    time: '05:00 PM',
    icon: require('../assets/overcast.png'),
    weather: 'Sunny',
    temp: '22°C',
  },
];

export const sevenDayWeather = [
  {
    id: 1,
    date: 'Feb 20',
    week: 'Today',
    icon: require('../assets/rain.png'),
    weather: 'mostly sunny',
    temp: '22/10°C',
  },
  {
    id: 2,
    date: 'Feb 21',
    week: 'Wed',
    icon: require('../assets/cloudy.png'),
    weather: 'overcast',
    temp: '22/10°C',
  },
  {
    id: 3,
    date: 'Feb 22',
    week: 'Thu',
    icon: require('../assets/overcast.png'),
    weather: 'rain',
    temp: '22/10°C',
  },
  {
    id: 4,
    date: 'Feb 23',
    week: 'Fri',
    icon: require('../assets/rain.png'),
    weather: 'partly cloudy',
    temp: '22/10°C',
  },
  {
    id: 5,
    date: 'Feb 24',
    week: 'Sat',
    icon: require('../assets/rising-sun.png'),
    weather: 'mostly sunny',
    temp: '22/10°C',
  },
  {
    id: 6,
    date: 'Feb 25',
    week: 'Sun',
    icon: require('../assets/rain.png'),
    weather: 'partly clody',
    temp: '22/10°C',
  },
  {
    id: 7,
    date: 'Feb 26',
    week: 'Mon',
    icon: require('../assets/sun.png'),
    weather: 'overcast',
    temp: '22/10°C',
  },
];
